# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c725c870bbe66962999410b2e1bf652c6287f5877eaace6ae3c3f1b40094321421ce5e2ab1616c3488eaf1cdc581cd192e30cbb0a925064250baeeca48330b9

test:
  secret_key_base: bc0e587c8459e4f5509257ce8a55e317795373f756faba4e870bd065f6c62b4095aac995634776c520814cc1e2b181e655b8b8741507a1f2672991749e232a59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
